Updated package.json with lodash-node dependency version | Fixes 'cannot find module 'lodash-node/underscore' issue.
Lodash-Node has been recently updated. It no longer has an 'underscore' folder and as a consequence there's an error:

```
Error: Cannot find module 'lodash-node/underscore'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
.................
```

This commit fixes the issue by using an appropriate version of `lodash`